// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfdsrtwjxwzwbrtfgypm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmZHNydHdqeHd6d2JydGZneXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTY3NjUsImV4cCI6MjA2NjY5Mjc2NX0.U5en8um4hygAKGIuesQLVJzlsfaunIIl0w2581xM78U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});